var mongoose = require('mongoose');
var Schema = mongoose.Schema;


var ontimeSchema = new Schema({
    _id: Number,
    YEAR: Number,
    QUARTER: Number,
    MONTH: Number,
    DAY_OF_MONTH: Number,
    DAY_OF_WEEK: Number,
    FL_DATE: String,
    UNIQUE_CARRIER: String,
    AIRLINE_ID: Number,
    CARRIER: String,
    TAIL_NUM: String,
    FL_NUM: Number,
    ORIGIN_AIRPORT_ID: Number, 
    ORIGIN_AIRPORT_SEQ_ID: Number, 
    ORIGIN_CITY_MARKET_ID: Number, 
    ORIGIN: String, 
    ORIGIN_CITY_NAME: String,
    ORIGIN_STATE_ABR: String, 
    ORIGIN_STATE_FIPS : Number, 
    ORIGIN_STATE_NM : String, 
    ORIGIN_WAC: Number, 
    DEST_AIRPORT_ID: Number, 
    DEST_AIRPORT_SEQ_ID: Number, 
    DEST_CITY_MARKET_I: Number, 
    DEST: String, 
    DEST_CITY_NAME: String, 
    DEST_STATE_ABR: String, 
    DEST_STATE_FIPS: Number, 
    DEST_STATE_NM: String, 
    DEST_WAC: Number, 
    CRS_DEP_TIME: Number, 
    DEP_TIME: Number, 
    DEP_DELAY: Number, 
    DEP_DELAY_NEW: Number, 
    DEP_DEL15: Number, 
    DEP_DELAY_GROUP: Number, 
    DEP_TIME_BLK: String, 
    TAXI_OUT: String, 
    WHEELS_OFF: String, 
    WHEELS_ON: String, 
    TAXI_IN: String, 
    CRS_ARR_TIME: Number, 
    ARR_TIME: Number, 
    ARR_DELAY: Number, 
    ARR_DELAY_NEW: Number, 
    ARR_DEL15: Number, 
    ARR_DELAY_GROUP: Number, 
    ARR_TIME_BLK: String, 
    CANCELLED: Number, 
    CANCELLATION_CODE: String, 
    DIVERTED: Number,
    CRS_ELAPSED_TIME: Number, 
    ACTUAL_ELAPSED_TIME: Number,
    AIR_TIME: String, 
    FLIGHTS: Number, 
    DISTANCE: Number, 
    DISTANCE_GROUP: Number, 
    CARRIER_DELAY: String, 
    WEATHER_DELAY: String, 
    NAS_DELAY: String, 
    SECURITY_DELAY: String, 
    LATE_AIRCRAFT_DELAY: String, 
    FIRST_DEP_TIME: String, 
    TOTAL_ADD_GTIME: String, 
    LONGEST_ADD_GTIME: String, 
    DIV_AIRPORT_LANDINGS: String, 
    DIV_REACHED_DEST: String, 
    DIV_ACTUAL_ELAPSED_TIME: String, 
    DIV_ARR_DELAY: String, 
    DIV_DISTANCE: String, 
    DIV1_AIRPORT: String, 
    DIV1_AIRPORT_ID: String, 
    DIV1_AIRPORT_SEQ_ID: String, 
    DIV1_WHEELS_ON: String, 
    DIV1_TOTAL_GTIME: String, 
    DIV1_LONGEST_GTIME: String, 
    DIV1_WHEELS_OFF: String, 
    DIV1_TAIL_NUM: String, 
    DIV2_AIRPORT: String, 
    DIV2_AIRPORT_ID: String, 
    DIV2_AIRPORT_SEQ_ID: String, 
    DIV2_WHEELS_ON: String, 
    DIV2_TOTAL_GTIME: String, 
    DIV2_LONGEST_GTIME: String, 
    DIV2_WHEELS_OFF: String, 
    DIV2_TAIL_NUM: String, 
    DIV3_AIRPORT: String, 
    DIV3_AIRPORT_ID: String, 
    DIV3_AIRPORT_SEQ_ID: String, 
    DIV3_WHEELS_ON: String, 
    DIV3_TOTAL_GTIME: String, 
    DIV3_LONGEST_GTIME: String, 
    DIV3_WHEELS_OFF: String, 
    DIV3_TAIL_NUM: String, 
    DIV4_AIRPORT: String, 
    DIV4_AIRPORT_ID: String, 
    DIV4_AIRPORT_SEQ_ID: String, 
    DIV4_WHEELS_ON: String, 
    DIV4_TOTAL_GTIME: String, 
    DIV4_LONGEST_GTIME: String, 
    DIV4_WHEELS_OFF: String, 
    DIV4_TAIL_NUM: String, 
    DIV5_AIRPORT: String, 
    DIV5_AIRPORT_ID: String, 
    DIV5_AIRPORT_SEQ_ID: String, 
    DIV5_WHEELS_ON: String, 
    DIV5_TOTAL_GTIME: String, 
    DIV5_LONGEST_GTIME: String, 
    DIV5_WHEELS_OFF: String, 
    DIV5_TAIL_NUM: String,
},
{
    collection: 'ontime'
});

var Model = mongoose.model('ontime', ontimeSchema);

module.exports = Model;